version: 2.1
orbs:
  node: circleci/node@4.5

jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - run: yarn install --frozen-lockfile # Use yarn install with frozen lockfile to ensure consistency
      # Run optional required steps before releasing
      # - run: yarn run build-script
      - run: npx semantic-release

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 20.14.0
      - release:
          requires:
            - node/test
