version: 2.1

orbs:
  node: circleci/node@5.2

# Orchestrate jobs using workflows

workflows:
  pokename-workflows:
    # jobs you want to run.
    jobs:
      - node/test:
          version: "20.14.0"
          pkg-manager: yarn
     - release:
        executor: node/default
        steps:
          - checkout
          - run: npm install
          - run: npx semantic-release
